- name: nginx install and run
  hosts: AzureVM
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  
  - name: update nginx default index page
    ansible.buildin.copy:
      dest: /var/www/html/index.nginx-debain.html
      content: "Welcome to Ezy DevOps\n"
      owner: www-data
      group: www-data
      mode: '0644'