- name: play-01
  hosts: ezydevops
  tasks:
  - name: print message play-01 and task-01
    ansible.builtin.debug:
      msg: "This from play 01 and task-01"

- name: play-02
  hosts: Gouri
  tasks:
  - name: print message play-02 and task-02
    ansible.builtin.debug:
      msg: "This from play-02 and task-02"   